# NumPy introduction

In [33]:
import numpy as np

## DataTypes & attributes

In [34]:
# NumPy's main datatype is ndarray
a1 = np.array([1, 2, 3])
a1

array([1, 2, 3])

In [35]:
type(a1)

numpy.ndarray

In [36]:
a2 = np.array([[1, 2.0, 3.3], [4, 5, 6.5]])
a3 = np.array(
    [[[1, 2, 3], [4, 5, 6], [7, 8, 9]], [[10, 11, 12], [13, 14, 15], [16, 17, 18]]]
)

In [37]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [38]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [39]:
a1.shape

(3,)

In [40]:
a2.shape

(2, 3)

In [41]:
a3.shape

(2, 3, 3)

In [42]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int64'), dtype('float64'), dtype('int64'))

In [43]:
a1.size, a2.size, a3.size

(3, 6, 18)

In [44]:
# Create a DataFrame from NumPy array
import pandas as pd

df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

# Creating arrays

In [45]:
sample_array = np.array([1, 2, 3])
sample_array

array([1, 2, 3])

In [46]:
sample_array.dtype

dtype('int64')

In [47]:
ones = np.ones((2, 3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [48]:
ones.dtype

dtype('float64')

In [49]:
type(ones)

numpy.ndarray

In [50]:
zeros = np.zeros((2, 3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [51]:
range_array = np.arange(0, 10, 2)
range_array

array([0, 2, 4, 6, 8])

In [52]:
random_array = np.random.randint(0, 10, size=(3, 5))
random_array

array([[5, 1, 5, 2, 5],
       [2, 2, 6, 5, 4],
       [3, 0, 9, 1, 0]])

In [53]:
random_array.shape

(3, 5)

In [54]:
random_array2 = np.random.random((5, 3))
random_array2

array([[0.89035743, 0.9311932 , 0.88853659],
       [0.95721931, 0.65405438, 0.89627323],
       [0.80208714, 0.31414271, 0.867836  ],
       [0.00343671, 0.56648721, 0.70498132],
       [0.06617462, 0.20838217, 0.31479331]])

In [55]:
random_array_3 = np.random.rand(5, 3)
random_array_3

array([[0.57014073, 0.06600274, 0.00519477],
       [0.87088175, 0.65530799, 0.3441139 ],
       [0.5771541 , 0.23980354, 0.01940007],
       [0.15122382, 0.01309613, 0.30049473],
       [0.01318948, 0.51083891, 0.14775479]])

In [56]:
# Pseudo-random numbers
# np.random.seed()
random_array_4 = np.random.randint(10, size=(5, 3))
random_array_4

array([[3, 5, 4],
       [6, 8, 9],
       [9, 0, 2],
       [6, 3, 4],
       [4, 9, 4]])

## 3. Viewing arrays and matrices

In [58]:
np.unique(random_array_4)

array([0, 2, 3, 4, 5, 6, 8, 9])

In [59]:
a3[:2, :2, :2]

array([[[ 1,  2],
        [ 4,  5]],

       [[10, 11],
        [13, 14]]])

In [60]:
a4 = np.random.randint(10, size=(2, 3, 4, 5))
a4

array([[[[6, 8, 0, 5, 6],
         [5, 7, 3, 3, 5],
         [5, 1, 0, 4, 4],
         [1, 4, 5, 5, 2]],

        [[1, 4, 6, 2, 0],
         [3, 2, 6, 7, 1],
         [5, 1, 5, 2, 4],
         [8, 6, 1, 7, 8]],

        [[1, 7, 9, 7, 5],
         [1, 9, 3, 2, 0],
         [9, 8, 4, 2, 6],
         [9, 4, 6, 0, 7]]],


       [[[1, 3, 5, 1, 1],
         [1, 3, 8, 5, 0],
         [1, 5, 2, 4, 7],
         [6, 5, 9, 1, 4]],

        [[7, 4, 0, 9, 4],
         [7, 0, 9, 7, 9],
         [5, 4, 9, 4, 6],
         [5, 9, 3, 1, 7]],

        [[3, 3, 1, 8, 3],
         [3, 4, 8, 3, 4],
         [0, 0, 3, 9, 0],
         [3, 0, 4, 1, 6]]]])

In [61]:
# Get the first 3 numbers of the inner most arrays
a4[:, :, :, :4]

array([[[[6, 8, 0, 5],
         [5, 7, 3, 3],
         [5, 1, 0, 4],
         [1, 4, 5, 5]],

        [[1, 4, 6, 2],
         [3, 2, 6, 7],
         [5, 1, 5, 2],
         [8, 6, 1, 7]],

        [[1, 7, 9, 7],
         [1, 9, 3, 2],
         [9, 8, 4, 2],
         [9, 4, 6, 0]]],


       [[[1, 3, 5, 1],
         [1, 3, 8, 5],
         [1, 5, 2, 4],
         [6, 5, 9, 1]],

        [[7, 4, 0, 9],
         [7, 0, 9, 7],
         [5, 4, 9, 4],
         [5, 9, 3, 1]],

        [[3, 3, 1, 8],
         [3, 4, 8, 3],
         [0, 0, 3, 9],
         [3, 0, 4, 1]]]])