# NumPy introduction

In [40]:
import numpy as np

## DataTypes & attributes

In [41]:
# NumPy's main datatype is ndarray
a1 = np.array([1, 2, 3])
a1

array([1, 2, 3])

In [42]:
type(a1)

numpy.ndarray

In [43]:
a2 = np.array([[1, 2.0, 3.3], [4, 5, 6.5]])
a3 = np.array(
    [[[1, 2, 3], [4, 5, 6], [7, 8, 9]], [[10, 11, 12], [13, 14, 15], [16, 17, 18]]]
)

In [44]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [45]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [46]:
a1.shape

(3,)

In [47]:
a2.shape

(2, 3)

In [48]:
a3.shape

(2, 3, 3)

In [49]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int64'), dtype('float64'), dtype('int64'))

In [50]:
a1.size, a2.size, a3.size

(3, 6, 18)

In [51]:
# Create a DataFrame from NumPy array
import pandas as pd

df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

# Creating arrays

In [52]:
sample_array = np.array([1, 2, 3])
sample_array

array([1, 2, 3])

In [53]:
sample_array.dtype

dtype('int64')

In [54]:
ones = np.ones((2, 3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [55]:
ones.dtype

dtype('float64')

In [56]:
type(ones)

numpy.ndarray

In [57]:
zeros = np.zeros((2, 3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [58]:
range_array = np.arange(0, 10, 2)
range_array

array([0, 2, 4, 6, 8])

In [59]:
random_array = np.random.randint(0, 10, size=(3, 5))
random_array

array([[4, 8, 7, 2, 7],
       [2, 5, 2, 7, 5],
       [7, 7, 2, 1, 7]])

In [60]:
random_array.shape

(3, 5)

In [61]:
random_array2 = np.random.random((5, 3))
random_array2

array([[0.888448  , 0.53555668, 0.01723749],
       [0.43220811, 0.79936216, 0.4925189 ],
       [0.37349416, 0.87090568, 0.08625   ],
       [0.24057134, 0.44084572, 0.08262707],
       [0.65974865, 0.31684116, 0.47843605]])

In [62]:
random_array_3 = np.random.rand(5, 3)
random_array_3

array([[0.60831398, 0.44071949, 0.16973574],
       [0.13430283, 0.29209435, 0.2254828 ],
       [0.06592787, 0.0685081 , 0.31952197],
       [0.31529375, 0.16055844, 0.66730021],
       [0.60492603, 0.51156097, 0.79480585]])

In [63]:
# Pseudo-random numbers
# np.random.seed()
random_array_4 = np.random.randint(10, size=(5, 3))
random_array_4

array([[8, 4, 4],
       [9, 9, 0],
       [5, 2, 1],
       [3, 3, 9],
       [5, 3, 0]])

## 3. Viewing arrays and matrices

In [64]:
np.unique(random_array_4)

array([0, 1, 2, 3, 4, 5, 8, 9])

In [65]:
a3[:2, :2, :2]

array([[[ 1,  2],
        [ 4,  5]],

       [[10, 11],
        [13, 14]]])

In [66]:
a4 = np.random.randint(10, size=(2, 3, 4, 5))
a4

array([[[[3, 6, 9, 6, 6],
         [4, 5, 5, 0, 9],
         [6, 0, 5, 9, 8],
         [2, 6, 5, 5, 7]],

        [[8, 0, 9, 4, 9],
         [4, 5, 5, 1, 2],
         [8, 1, 5, 8, 7],
         [1, 0, 6, 9, 7]],

        [[2, 8, 6, 0, 5],
         [2, 3, 0, 8, 7],
         [3, 3, 9, 8, 3],
         [3, 2, 0, 9, 2]]],


       [[[6, 9, 2, 7, 6],
         [3, 7, 2, 7, 5],
         [0, 5, 0, 8, 8],
         [8, 9, 4, 0, 7]],

        [[0, 8, 8, 4, 7],
         [6, 3, 4, 7, 6],
         [5, 3, 2, 5, 7],
         [0, 1, 7, 4, 5]],

        [[0, 9, 8, 0, 0],
         [5, 2, 1, 6, 1],
         [3, 3, 6, 3, 8],
         [6, 0, 7, 8, 8]]]])

In [67]:
# Get the first 3 numbers of the inner most arrays
a4[:, :, :, :4]

array([[[[3, 6, 9, 6],
         [4, 5, 5, 0],
         [6, 0, 5, 9],
         [2, 6, 5, 5]],

        [[8, 0, 9, 4],
         [4, 5, 5, 1],
         [8, 1, 5, 8],
         [1, 0, 6, 9]],

        [[2, 8, 6, 0],
         [2, 3, 0, 8],
         [3, 3, 9, 8],
         [3, 2, 0, 9]]],


       [[[6, 9, 2, 7],
         [3, 7, 2, 7],
         [0, 5, 0, 8],
         [8, 9, 4, 0]],

        [[0, 8, 8, 4],
         [6, 3, 4, 7],
         [5, 3, 2, 5],
         [0, 1, 7, 4]],

        [[0, 9, 8, 0],
         [5, 2, 1, 6],
         [3, 3, 6, 3],
         [6, 0, 7, 8]]]])

## 4. Manipulating & Comparing arrays

### Arithmetic

In [68]:
a1

array([1, 2, 3])

In [69]:
ones = np.ones(3)
ones

array([1., 1., 1.])

In [70]:
a1 + ones

array([2., 3., 4.])

In [71]:
a1 * ones

array([1., 2., 3.])

In [72]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [73]:
a1 * a2

array([[ 1. ,  4. ,  9.9],
       [ 4. , 10. , 19.5]])

In [74]:
3 * 6.5

19.5

In [75]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [76]:
a2 * a3

ValueError: operands could not be broadcast together with shapes (2,3) (2,3,3) 

In [ ]:
a1 / ones

array([1., 2., 3.])

In [ ]:
a2 / a1

array([[1.        , 1.        , 1.1       ],
       [4.        , 2.5       , 2.16666667]])

In [ ]:
a2 // a1

array([[1., 1., 1.],
       [4., 2., 2.]])

In [ ]:
a2**2

array([[ 1.  ,  4.  , 10.89],
       [16.  , 25.  , 42.25]])

In [ ]:
np.square(a2)

array([[ 1.  ,  4.  , 10.89],
       [16.  , 25.  , 42.25]])

In [ ]:
np.add(a1, ones)

array([2., 3., 4.])

### Aggregation