# NumPy introduction

In [11]:
import numpy as np

## DataTypes & attributes

In [15]:
# NumPy's main datatype is ndarray
a1 = np.array([1, 2, 3])
a1

array([1, 2, 3])

In [13]:
type(a1)

numpy.ndarray

In [18]:
a2 = np.array([[1, 2.0, 3.3], [4, 5, 6.5]])
a3 = np.array(
    [[[1, 2, 3], [4, 5, 6], [7, 8, 9]], [[10, 11, 12], [13, 14, 15], [16, 17, 18]]]
)

In [19]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [20]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])